const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function updateArray(){const r=+$('[id=rows]').value,c=+$('[id=cols]').value,b=+$('[id=bytes]').value;$('#rowsOut').value=r;$('#colsOut').value=c;$('#shapeOut').textContent=`(${r}, ${c})`;$('#sizeOut').textContent=r*c;$('#nbytesOut').textContent=r*c*b}$$('#rows,#cols,#bytes').forEach(el=>el.addEventListener('input',updateArray));

let memoryMode='slice',memory=[0,1,2,3,4];function drawMemory(){const selected=memoryMode==='boolean'?[2,3,4]:[1,2,3];$('#originalCells').innerHTML=memory.map((v,i)=>`<span class="cell ${selected.includes(i)?'selected':''} ${v===99?'changed':''}">${v}</span>`).join('');$('#memoryMessage').textContent=memoryMode==='slice'?'Result is a view. The highlighted cells share memory with a.':'Result is a copy. It contains selected values in new memory.'}$$('[data-memory]').forEach(b=>b.onclick=()=>{memoryMode=b.dataset.memory;memory=[0,1,2,3,4];$$('[data-memory]').forEach(x=>x.classList.toggle('active',x===b));drawMemory()});$('#mutate').onclick=()=>{if(memoryMode==='slice')memory[1]=99;drawMemory()};drawMemory();

function drawIndex(){const mode=$('#indexMode').value,chosen=[];for(let n=0;n<24;n++){const r=Math.floor(n/6),c=n%6;if(mode==='block'&&r>=1&&r<3&&c>=2&&c<5)chosen.push(n);if(mode==='stride'&&r%2===0&&c%3===0)chosen.push(n);if(mode==='mask'&&n>10)chosen.push(n)}$('#indexMatrix').innerHTML=Array.from({length:24},(_,n)=>`<span class="cell ${chosen.includes(n)?'selected':''}">${n}</span>`).join('');$('#indexAnswer').textContent=mode==='block'?'Result shape: (2, 3) · view':mode==='stride'?'Result shape: (2, 2) · view':'Result shape: (13,) · copy'}$('#indexMode').oninput=drawIndex;drawIndex();

$('#axisMatrix').innerHTML=[0,1,2,3,4,5].map(n=>`<span class="cell">${n}</span>`).join('');let axis='0';function updateAxis(){const keep=$('#keepdims').checked;const data={0:['Remove axis 0. One result remains for each column.','[3, 5, 7]',keep?'shape (1, 3)':'shape (3,)'],1:['Remove axis 1. One result remains for each row.','[3, 12]',keep?'shape (2, 1)':'shape (2,)'],all:['Remove every axis. The result is one scalar.','15',keep?'shape (1, 1)':'shape ()']}[axis];$('#axisSentence').textContent=data[0];$('#axisValues').textContent=data[1];$('#axisShape').textContent=data[2]}$$('[data-axis]').forEach(b=>b.onclick=()=>{axis=b.dataset.axis;$$('[data-axis]').forEach(x=>x.classList.toggle('active',x===b));updateAxis()});$('#keepdims').oninput=updateAxis;

function updateNan(){const vals=$$('.nan-value:checked').map(x=>x.value==='nan'?NaN:+x.value),valid=vals.filter(Number.isFinite),ordinary=vals.some(Number.isNaN)?NaN:valid.reduce((a,b)=>a+b,0)/valid.length,nanmean=valid.length?valid.reduce((a,b)=>a+b,0)/valid.length:NaN;$('#meanOut').textContent=Number.isNaN(ordinary)?'NaN':ordinary.toFixed(3);$('#nanmeanOut').textContent=Number.isNaN(nanmean)?'NaN':nanmean.toFixed(3);$('#validCount').textContent=`${valid.length} valid value${valid.length===1?'':'s'}`}$$('.nan-value').forEach(x=>x.oninput=updateNan);

function shape(text){const nums=text.split(',').map(x=>+x.trim()).filter(Number.isFinite);return nums.length?nums:null}function checkBroadcast(){const a=shape($('#shapeA').value),b=shape($('#shapeB').value);if(!a||!b)return;const n=Math.max(a.length,b.length),aa=Array(n-a.length).fill(1).concat(a),bb=Array(n-b.length).fill(1).concat(b),ok=aa.every((v,i)=>v===bb[i]||v===1||bb[i]===1),out=aa.map((v,i)=>Math.max(v,bb[i]));$('#alignedA').textContent=`(${aa.join(', ')})`;$('#alignedB').textContent=`(${bb.join(', ')})`;const result=$('#broadcastResult');result.textContent=ok?`Compatible → (${out.join(', ')})`:'Not compatible';result.classList.toggle('fail',!ok)}$('#checkBroadcast').onclick=checkBroadcast;

function updateOverflow(){const p=+$('#pixel').value,a=+$('#addValue').value;$('#pixelOut').value=p;$('#addOut').value=a;$('#overflowOut').textContent=`${p} + ${a} = ${(p+a)%256}`;$('#safeOut').textContent=`${p} + ${a} = ${p+a}`}$$('#pixel,#addValue').forEach(x=>x.oninput=updateOverflow);

$$('[data-op]').forEach(b=>b.onclick=()=>{const matrix=b.dataset.op==='matrix';$$('[data-op]').forEach(x=>x.classList.toggle('active',x===b));$('#opTitle').textContent=matrix?'Combine rows of A with columns of B':'Pair corresponding positions';$('#opBody').textContent=matrix?'The inner dimensions must match. The output keeps the outer dimensions.':'Shapes must be equal or broadcast-compatible. The output follows the broadcast shape.';$('#opShape').textContent=matrix?'(2, 3) @ (3, 2) → (2, 2)':'(2, 3) * (2, 3) → (2, 3)'});

const questions=[['What is the shape of np.arange(24).reshape(2,3,4).sum(axis=-1)?','(2, 3). Axis -1 is the final dimension, so the length 4 disappears.'],['Does changing a[1:4] affect a?','Usually yes. Basic slicing returns a view that shares memory.'],['Can shapes (3,5) and (5,1) be added?','No. Right-aligned dimensions compare as 5 vs 1, then 3 vs 5. The second pair fails.'],['What happens after a[a>1][0] = 99?','The original array stays unchanged because boolean indexing created a temporary copy.'],['Why does np.nanmean([NaN, 2]) return 2?','It skips NaN and computes the mean over the one valid value.']];$('#quiz').innerHTML=questions.map((q,i)=>`<article class="quiz-item"><p>${i+1}. ${q[0]}</p><button data-reveal="${i}">Reveal explanation</button><div class="feedback" id="feedback${i}">${q[1]}</div></article>`).join('');let checked=new Set();$$('[data-reveal]').forEach(b=>b.onclick=()=>{const i=+b.dataset.reveal;checked.add(i);$(`#feedback${i}`).classList.toggle('show');b.textContent=$(`#feedback${i}`).classList.contains('show')?'Hide explanation':'Reveal explanation';$('#score').textContent=`${checked.size} of 5 checked`});

const sections=$$('.lesson'),links=$$('.sidebar nav a');const observer=new IntersectionObserver(entries=>{entries.filter(e=>e.isIntersecting).forEach(e=>links.forEach(a=>a.classList.toggle('active',a.hash===`#${e.target.id}`)))},{rootMargin:'-25% 0px -65%'});sections.forEach(s=>observer.observe(s));addEventListener('scroll',()=>{const h=document.documentElement;$('#progressBar').style.width=`${100*h.scrollTop/(h.scrollHeight-h.clientHeight)}%`},{passive:true});


